syntax on
map t :tabedit 
set autoindent
set autoread
set expandtab
set foldmethod=marker
set hlsearch
set nu
set shiftwidth=4
set tabstop=4
set vb
map <C-p> :vert term<CR><C-w>r

" Set colourscheme and override background (setting it to transparent)
colorscheme torte
highlight Normal guibg=NONE ctermbg=NONE
highlight NonText ctermbg=NONE
highlight EndOfBuffer ctermbg=NONE
highlight SignColumn ctermbg=NONE

