#!/bin/bash
# Builds a unified AGENTS.md from template.md and CLAUDE.md,
# recursively expanding @filename.md references inline.
# Run periodically or after editing any source file.

DIR="$(cd "$(dirname "$0")" && pwd)"
OUT="$DIR/AGENTS.md"

# Recursively expand @filename.md references in a file.
# Tracks visited files to prevent circular includes.
expand_file() {
    local file="$1"
    local base_dir
    base_dir="$(dirname "$file")"
    shift
    local visited=("$@")

    # Circular include guard
    local real_path
    real_path="$(realpath "$file" 2>/dev/null || echo "$file")"
    for v in "${visited[@]}"; do
        if [ "$v" = "$real_path" ]; then
            echo "<!-- WARNING: circular include detected for $(basename "$file"), skipping -->"
            return
        fi
    done
    visited+=("$real_path")

    while IFS= read -r line || [ -n "$line" ]; do
        # Match lines that are just @filename.md (with optional leading whitespace)
        if [[ "$line" =~ ^[[:space:]]*@([A-Za-z0-9_/.:-]+\.md)[[:space:]]*$ ]]; then
            local ref="${BASH_REMATCH[1]}"
            local ref_path="$base_dir/$ref"
            if [ -f "$ref_path" ]; then
                expand_file "$ref_path" "${visited[@]}"
            else
                echo "<!-- WARNING: $ref not found, skipping -->"
                echo "$line"
            fi
        else
            echo "$line"
        fi
    done < "$file"
}

# Header
cat > "$OUT" << 'EOF'
<!-- AUTO-GENERATED by build-agents-md.sh — do not edit directly -->
<!-- Edit template.md, CLAUDE-template.md, CLAUDE.md, or include/*.md instead -->

EOF

# Core files in order — expand @includes recursively
for file in "$DIR/template.md"; do
    if [ -f "$file" ]; then
        echo "<!-- source: $(basename "$file") -->" >> "$OUT"
        expand_file "$file" >> "$OUT"
        echo -e "\n" >> "$OUT"
    else
        echo "WARNING: $file not found, skipping" >&2
    fi
done

echo "Built $OUT ($(wc -l < "$OUT") lines)"
